# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    # Étape 3 : Construire l'image Docker
    - name: Build Docker image
      run: |
        docker build -t collecte .

    # Étape 4 : Archiver l'image Docker
    - name: Save Docker image as tar
      run: |
        docker save collecte > collecte.tar
    - uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: collecte.tar

    - uses: actions/download-artifact@v3
      with:
        name: docker-image
    - name: Load the Docker image
      run: docker load < collecte.tar
    - name: Upload Docker image to VPS
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: collecte.tar
        target: /home/${{ secrets.SERVER_USER }}
    - name: Deploy on VPS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          set -e
          docker stop collecte-container || true
          docker rm collecte-container || true
          docker load < /home/${{ secrets.SERVER_USER }}/collecte.tar
          docker run -d --name collecte-container -p 5000:5000 collecte:latest
          # rm -f /home/${{ secrets.SERVER_USER }}/collecte.tar
