# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Étape 3 : Construire l'image Docker
    - name: Build Docker image
      run: |
        docker build -t collecte:latest .

    # Étape 4 : Archiver l'image Docker
    - name: Save Docker image as tar
      run: |
        docker save collect:latest -o yourapp.tar
      # Sauvegarder l'archive pour le transfert
      id: save

    # Étape 5 : Transférer l'image Docker sur le VPS
    - name: Upload Docker image to VPS
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.SECRET_HOST }}
        username: ${{ secrets.SECRET_USERNAME }}
        password: ${{ secrets.SECRET_PASSWORD }}
        source: collecte.tar
        target: /home/${{ secrets.SECRET_USERNAME }}/collecte.tar

    # Étape 6 : Charger et exécuter l'image sur le VPS
    - name: Deploy on VPS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.SECRET_USERNAME }}
        password: ${{ secrets.SECRET_PASSWORD }}
        script: |
          docker load -i /home/${{ secrets.SECRET_USERNAME }}/collecte.tar
          docker stop collecte || true
          docker rm collecte || true
          docker run -d --name collecte -p 5000:8080 collecte:latest
